spring.datasource.url=${DATABASE_URL:jdbc:h2:file:./data/videogamesdb}
spring.datasource.username=${PGUSER:sa}
spring.datasource.password=${PGPASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=miClaveSecretaSuperSeguraParaJWT2024VideogamesAPI
jwt.expiration=86400000

spring.security.user.name=admin
spring.security.user.password=admin

springdoc.packages-to-scan=com.mmorenodev.videogames_api.controller
server.port=8081