spring.datasource.url=jdbc:h2:file:./data/videogamesdbspring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=miClaveSecretaSuperSeguraParaJWT2024videogames_api
jwt.expiration=86400000

spring.security.user.name=admin
spring.security.user.password=admin
server.port=8081
springdoc.packages-to-scan=com.mmorenodev.videogames_api.controller